### ISSUE TITLE
WASI problem

### ISSUE THREAD

**Issue by Rui-Gan** [tinygo-org/tinygo#3834]
I am trying to compile the eKuiper project(https://github.com/lf-edge/ekuiper) to Wasi and then use wasmedge to run the compiled binary file. I used TinyGo to compile eKuiper to Wasi, but encountered issues.

When I ran the command below to compile eKuiper to Wasi:
```
tinygo build -o kuperd.wasm -target wasi cmd/kuiperd/main.go
```
I received the following error message:
```
# golang.org/x/sys/unix
../../../go/pkg/mod/golang.org/x/sys@v0.10.0/unix/syscall_linux.go:1901:64: undefined: syscall.Rlimit
../../../go/pkg/mod/golang.org/x/sys@v0.10.0/unix/syscall_linux.go:1906:50: undefined: syscall.Rlimit
../../../go/pkg/mod/golang.org/x/sys@v0.10.0/unix/syscall_linux.go:1906:79: undefined: syscall.Rlimit
../../../go/pkg/mod/golang.org/x/sys@v0.10.0/unix/syscall_unix.go:595:17: undefined: syscall.Setrlimit
../../../go/pkg/mod/golang.org/x/sys@v0.10.0/unix/syscall_unix.go:595:47: undefined: syscall.Rlimit
```

I am not sure what causes this error and would appreciate any help. I would like to know why this issue occurs and how to resolve it.

**Comment by HarikrishnanBalagopal** [comment]
> syscall.Rlimit

Resource limit I think https://pkg.go.dev/syscall#Rlimit
https://pkg.go.dev/syscall#Setrlimit
https://linux.die.net/man/2/setrlimit

**Comment by aykevl** [comment]
This error message means that you are (directly or indirectly) importing golang.org/x/sys, which as you see isn't currently supported. Hopefully it will be once we switch to GOOS=wasip1 support (we currently use linux/arm for lack of real WASI support in the Go standard library).

**Comment by Rui-Gan** [comment]
Thanks for your reply,

**Comment by aykevl** [comment]
Also see: #3861

**Comment by maggie44** [comment]
Did you find a way to track down the package that was causing the issue? I am not building WASI, just the standard tinygo build but the same issue:

```
vendor/golang.org/x/sys/unix/syscall_unix.go:603:17: undefined: syscall.Setrlimit
vendor/golang.org/x/sys/unix/syscall_unix.go:603:47: undefined: syscall.Rlimit
```

Can't track which package is trying to call it though.

**Comment by aykevl** [comment]
You can try `tinygo list -deps -json -target wasi` and inspect the output.

**Comment by inliquid** [comment]
Also encountered this issue with some gRPC (proto definitions) dependencies.

**Comment by aykevl** [comment]
You can try `GOOS=wasip1 GOARCH=wasm tinygo ...` instead of `tinygo -target=wasi`. This means we use the standard library WASI support instead of our custom variant, which _might_ get more code to compile.

**Comment by inliquid** [comment]
Thank you, will this approach become a standard way of compiling to WASI at some point?

**Comment by aykevl** [comment]
Yes. It only works in Go 1.21+ and right now we support Go versions down to Go 1.18 so I think we should wait a bit before changing the default.
