### ISSUE TITLE
Prometheus not compatible with tinygo?

### ISSUE THREAD

**Issue by f0o** [tinygo-org/tinygo#3879]
Possibly related to https://github.com/tinygo-org/tinygo/issues/3705 ?

```
# github.com/prometheus/client_golang/prometheus/internal
../../../../go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/internal/go_runtime_metrics.go:42:27: d.Name undefined (type *metrics.Description has no field or method Name)
../../../../go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/internal/go_runtime_metrics.go:65:7: d.Cumulative undefined (type *metrics.Description has no field or method Cumulative)
../../../../go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/internal/go_runtime_metrics.go:65:23: d.Kind undefined (type *metrics.Description has no field or method Kind)
../../../../go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/internal/go_runtime_metrics.go:65:39: undefined: metrics.KindFloat64Histogram
../../../../go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/internal/go_runtime_metrics.go:70:11: d.Kind undefined (type *metrics.Description has no field or method Kind)
../../../../go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/internal/go_runtime_metrics.go:71:15: undefined: metrics.KindUint64
../../../../go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/internal/go_runtime_metrics.go:72:15: undefined: metrics.KindFloat64
../../../../go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/internal/go_runtime_metrics.go:73:15: undefined: metrics.KindFloat64Histogram
```

I'm not even sure where to start looking on this one; I cleared the modcache and let tinygo download the modules fresh but the error is a bit generic.

It works fine on Go 1.19+

**Comment by cpanato** [comment]
go the same issue, and not sure how to fix it :/

**Comment by aykevl** [comment]
The best way to get this working would be to extend the stub runtime/metrics package that got added in this PR: https://github.com/tinygo-org/tinygo/pull/3709

**Comment by v1rtl** [comment]
lack of support for Prometheus blocks tinygo compilation on my end too

```
../../go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_client.go:19:2: package net/http/httptrace is not in std (/Users/pasha/Library/Caches/tinygo/goroot-c01de6aa7b7aa1637e28124f5907518c32028f3be368ab6a8ef8f7e2ae93c417/src/net/http/httptrace)
```

**Comment by deadprogram** [comment]
Please see https://github.com/tinygo-org/tinygo/pull/4990

**Comment by cpanato** [comment]
seems have a new issue

```
# github.com/prometheus/procfs
../../../../pkg/mod/github.com/prometheus/procfs@v0.16.1/fs_statfs_type.go:25:18: undefined: syscall.Statfs_t
../../../../pkg/mod/github.com/prometheus/procfs@v0.16.1/fs_statfs_type.go:26:17: undefined: syscall.Statfs
../../../../pkg/mod/github.com/prometheus/procfs@v0.16.1/proc_stat.go:214:20: undefined: os.Getpagesize
```

**Comment by v1rtl** [comment]
getting there step by step

probably those could be mocked as well - I'll see if I manage to do that
