### PR TITLE
Add ESP-IDF build targets

### PR DESCRIPTION
**Pull request by hectorchu**
This PR adds ESP-IDF build targets for esp32c3 and esp32s3.

This allows you to build a relocatable object file which can be bundled inside a static library archive and used as-is in ESP-IDF projects.

### CODE REVIEW

**Comment by b0ch3nski** [comment]
This looks quite cool! Can you provide some example on how are you using this?

**Comment by hectorchu** [comment]
Sure. I am linking a Go module into a regular ESP-IDF project.

If you want code, see:

The Go module entry point
https://github.com/ltcmweb/seedsigner/blob/micropy/src/mweb/mweb.go

The micropython binding to the Go module
https://github.com/ltcmweb/seedsigner-micropython-builder/blob/main/bindings/modmweb_bindings.c

**Comment by hectorchu** [comment]
And the Go code runs in its own thread:
https://github.com/ltcmweb/seedsigner/blob/micropy/src/mweb/mweb.py

**Comment by b0ch3nski** [comment]
Woah, I wasn't expecting also Python being involved here. So if I understand this correctly, you are 'exporting' Go module that is then called from Python using the C bridge, right? Could you share a reason behind this?

**Comment by hectorchu** [comment]
Can you specify your question a bit clearer? Because right now my reasons for doing it this way is because the requirements demanded it. I was not willing to rewrite the entire Go module in C.

File: targets/esp32s3-idf.json
Comment (aykevl) [inline targets/esp32s3-idf.json:1]: Please add `esp32s3-idf` to `TestClangAttributes`, and add a smoke test.

File: targets/esp32c3-idf.json
Comment (aykevl) [inline targets/esp32c3-idf.json:1]: Please add `esp32c3-idf` to `TestClangAttributes`, and also add a smoke test to GNUmakefile.

File: targets/esp32c3-idf.json [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+	"build-tags": ["espidf", "esp"],
```
Comment (aykevl) [inline targets/esp32c3-idf.json:4]: Since you are not defining `esp32c3`, I assume it is okay for this target to be entirely without support from the machine package?

File: src/runtime/runtime_espidf.go
Comment (aykevl) [inline src/runtime/runtime_espidf.go:1]: Can you add a bit more documentation somewhere (this file, for example) describing how to use this target?

File: src/runtime/runtime_espidf.go [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+	tv_sec  int64
+	tv_nsec int32
+}
+
+//export clock_gettime
+func clock_gettime(clock int32, ts *timespec)
+
+func getTime(clock int32) uint64 {
+	var ts timespec
+	clock_gettime(clock, &ts)
```
Comment (aykevl) [inline src/runtime/runtime_espidf.go:70]: Note that this might result in a heap allocation, which might not be intended (especially in a potentially time sensitive function).

File: src/runtime/runtime_espidf.go [hunk 3]
```diff
@@ -0,0 +1,128 @@
...
+}
+
+//export usleep
+func usleep(usec uint) int
+
+func sleepTicks(d timeUnit) {
+	usleep(uint(d / 1e3))
+}
+
+const baremetal = true
```
Comment (aykevl) [inline src/runtime/runtime_espidf.go:97]: It's sort of in between now: ESP-IDF is kind of like an OS.
But since it isn't actually used (only use is in gc_blocks.go and it doesn't matter since `hasScheduler` is also false) it may be worth setting to `false` since what this actually controls is interrupt handling in the GC.

File: src/device/esp/esp32s3-stack.S
Comment (aykevl) [inline src/device/esp/esp32s3-stack.S:1]: Why did you move this to a new file? (Note that as long as `tinygo_scanCurrentStack` is not called it will be removed from the binary by the linker).

File: builder/build.go [hunk 4]
```diff
@@ -189,7 +189,7 @@ func Build(pkgName, outpath, tmpdir string, config *compileopts.Config) (BuildRe
 		defer unlock()
 		libcDependencies = append(libcDependencies, libcJob)
 		libcDependencies = append(libcDependencies, makeMinGWExtraLibs(tmpdir, config.GOARCH())...)
-	case "":
+	case "", "none":
```
Comment (aykevl) [inline builder/build.go:191]: Why not just keep it as an empty string?

**Review by aykevl — COMMENTED** [review]
Looks reasonable to me (but see the comments below).

Others (@deadprogram etc) have an opinion on this? This doesn't seem too invasive of a change, though I'm not sure we can confidently support this across all ESP-IDF versions etc.

Also, looks like this needs to be rebased on dev to merge conflicts with #5453.

File: builder/build.go (hunk 4 above)
Comment (hectorchu) [reply builder/build.go:191]: It doesn't work. You can't set the libc to an empty string in the target json, it doesn't override and unset any base target setting.

File: src/device/esp/esp32s3-stack.S
Comment (hectorchu) [reply src/device/esp/esp32s3-stack.S:1]: I think its because it still needs tinygo_scanCurrentStack for the GC. Without importing the other definitions in esp32s3.S which cause multiple definitions if I remember correctly.

File: src/runtime/runtime_espidf.go (hunk 2 above)
Comment (hectorchu) [reply src/runtime/runtime_espidf.go:70]: Right, but how would I ensure the struct is allocated on the stack? Is there no escape analysis?

File: builder/build.go (hunk 4 above)
Comment (hectorchu) [reply builder/build.go:191]: It's because in the json, the empty string is omitted (because of omitempty), so the setting never gets set to the empty string.

**Comment by deadprogram** [comment]
@hectorchu can yoou please resolve any merge conflicts? Thank you.

File: targets/esp32c3-idf.json [hunk 5]
```diff
@@ -0,0 +1,15 @@
...
...sqosid,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-supm,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-svvptc,-v,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xesppie,-xmipscmove,-xmipslsp,-xsfcease,-xsfvcp,-xsfvfnrclipxfqf,-xsfvfwmaccqqq,-xsfvqmaccdod,-xsfvqmaccqoq,-xsifivecdiscarddlone,-xsifivecflushdlone,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-xwchc,-za128rs,-za64rs,-zaamo,-zabha,-zacas,-zalrsc,-zama16b,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfbfmin,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zicsr,-zifencei,-zihintntl,-zihintpause,-zihpm,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-ztso,-zvbb,-zvbc,-zve32f,-zve32x,-zve64d,-zve64f,-zve64x,-zvfbfmin,-zvfbfwma,-zvfh,-zvfhmin,-zvkb,-zvkg,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknhb,-zvks,-zvksc,-zvksed,-zvksg,-zvksh,-zvkt,-zvl1024b,-zvl128b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl32b,-zvl4096b,-zvl512b,-zvl64b,-zvl65536b,-zvl8192b",
```
Comment (deadprogram) [inline targets/esp32c3-idf.json:3]: The format for this has changed a bit in the latest `dev` @hectorchu you can probably remove quite a bit. Please see https://github.com/tinygo-org/tinygo/blob/dev/targets/esp32c3.json

File: targets/esp32s3-idf.json
Comment (deadprogram) [reply targets/esp32s3-idf.json:1]: You need a smoke test please.

File: src/runtime/runtime_espidf.go
Comment (deadprogram) [reply src/runtime/runtime_espidf.go:1]: Some docs, yes please.
