### ISSUE TITLE
missing `net.Buffers`

### ISSUE THREAD

**Issue by nikpivkin** [tinygo-org/tinygo#4166]
Hi all!

I encountered the following error after upgrading tinygo from 0.29.0 to 0.31.0:
```bash
Error: ../../../../../../../go/pkg/mod/github.com/mailru/easyjson@v0.7.7/buffer/pool.go:171:14: undefined: net.Buffers
```
I did a little research and found out that `net.Buffers` was added in [this](https://github.com/tinygo-org/net/commit/c954718d79c8ad220f30fe5d2cc67fab185a2c66) commit but was later removed in [this](https://github.com/tinygo-org/net/commit/693edae782b7a2e82a7686dc7cd8bf37009bb8d9#diff-2fcb413ecd003cbcb8e5d2e08c7a80600a5b2da58869167c7dcb6f6f99752984L220) commit. Was there a reason for this?

The commit that removed net.Buffers contained the go1.19.3 source code, but [net.Buffers](https://cs.opensource.google/go/go/+/refs/tags/go1.19.3:src/net/net.go;l=712) is present.

**Comment by deadprogram** [comment]
cc @scottfeldman

**Comment by deadprogram** [comment]
Reopening to tag for `net-release`

**Comment by deadprogram** [comment]
@nikpivkin is there any way you can confirm that our fix solves your problem?

**Comment by deadprogram** [comment]
The fix has been released as part of 0.31.2 so now closing. Please reopen if needed, and thank you!
