### PR TITLE
test: print package name when compilation failed

### PR DESCRIPTION
**Pull request by aykevl**
Before this patch, a compile error would prevent the 'ok' or 'FAIL' line to be printed. That's unexpected. This patch changes the code in such a way that it's obvious a test result line is printed in all cases.

Found while working on Go 1.20.

### CODE REVIEW

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by deadprogram** [comment]
Seems like something did not work as expected here @aykevl please check CI fails.

**Comment by aykevl** [comment]
This should fix the CI error.

**Comment by deadprogram** [comment]
Thanks @aykevl and @dgryski now merging.
