### PR TITLE
compiler: implement go:cgo_import_dynamic and lower Darwin cgo import trampolines (#5604)

### LINKED ISSUE #5365: Tinygo doesn't build bubbletea/huh CLI applications on macOS.
I tried to build a CLI using bubbletea/huh in macOS.

It spits out errors when using `-x` flag:

```
../../go/pkg/mod/golang.org/x/sys@v0.43.0/unix/zsyscall_darwin_arm64.go:275: linker could not find symbol _golang.org/x/sys/unix.syscall_syscall6
../../go/pkg/mod/golang.org/x/sys@v0.43.0/unix/zsyscall_darwin_arm64.go:734: linker could not find symbol _golang.org/x/sys/unix.syscall_syscall
../../go/pkg/mod/golang.org/x/sys@v0.43.0/unix/zsyscall_darwin_arm64.go:1080: linker could not find symbol _golang.org/x/sys/unix.syscall_syscall
../../go/pkg/mod/golang.org/x/sys@v0.43.0/unix/zsyscall_darwin_arm64.go:1915: linker could not find symbol _golang.org/x/sys/unix.syscall_syscall
../../go/pkg/mod/golang.org/
```

When I try to cross-compile for windows:

```
$ GOOS=windows tinygo build 
open /opt/homebrew/Cellar/tinygo/0.41.1/lib/mingw-w64/mingw-w64-headers/crt/_mingw.h.in: no such file or directory

```

When I try to cross-compile for linux:

```
$ GOOS=linux tinygo build 
Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
```

```
$ tinygo version
tinygo version 0.41.1 darwin/arm64 (using go version go1.26.1 and LLVM version 20.1.1)
```

```
module x

go 1.26.1

require (
	charm.land/huh/v2 v2.0.3
	charm.land/lipgloss/v2 v2.0.3
	github.com/charmbracelet/x/exp/strings v0.1.0
)

require (
	charm.land/bubbles/v2 v2.0.0 // indirect
	charm.land/bubbletea/v2 v2.0.2 // indirect
	github.com/atotto/clipboard v0.1.4 // indirect
	github.com/catppuccin/go v0.2.0 // indirect
	github.com/charmbracelet/colorprofile v0.4.3 // indirect
	github.com/charmbracelet/ultraviolet v0.0.0-20260205113103-524a6607adb8 // indirect
	github.com/charmbracelet/x/ansi v0.11.7 // indirect
	github.com/charmbracelet/x/exp/ordered v0.1.0 // indirect
	github.com/charmbracelet/x/term v0.2.2 // indirect
	github.com/charmbracelet/x/termios v0.1.1 // indirect
	github.com/charmbracelet/x/windows v0.2.2 // indirect
	github.com/clipperhouse/displaywidth v0.11.0 // indirect
	github.com/clipperhouse/uax29/v2 v2.7.0 // indirect
	github.com/dustin/go-humanize v1.0.1 // indirect
	github.com/lucasb-eyer/go-colorful v1.4.0 // indirect
	github.com/mattn/go-runewidth v0.0.23 // indirect
	github.com/mitchellh/hashstructure/v2 v2.0.2 // indirect
	github.com/muesli/cancelreader v0.2.2 // indirect
	github.com/rivo/uniseg v0.4.7 // indirect
	github.com/xo/terminfo v0.0.0-20220910002029-abceb7e1c41e // indirect
	golang.org/x/sync v0.19.0 // indirect
	golang.org/x/sys v0.43.0 // indirect
)

```

```go
package main

import (
	"errors"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"
	
	"charm.land/huh/v2"
	"charm.land/huh/v2/spinner"
	"charm.land/lipgloss/v2"
	xstrings "github.com/charmbracelet/x/exp/strings"
)

type Spice int

const (
	Mild Spice = iota + 1
	Medium
	Hot
)

func (s Spice) String() string {
	switch s {
		case Mild:
		return "Mild "
		case Medium:
		return "Medium-Spicy "
		case Hot:
		return "Spicy-Hot "
		default:
		return ""
	}
}

type Order struct {
	Burger       Burger
	Side         string
	Name         string
	Instructions string
	Discount     bool
}

type Burger struct {
	Type     string
	Toppings []string
	Spice    Spice
}

func main() {
	var burger Burger
	order := Order{Burger: burger}
	
	// Should we run in accessible mode?
	accessible, _ := strconv.ParseBool(os.Getenv("ACCESSIBLE"))
	
	form := huh.NewForm(
		huh.NewGroup(huh.NewNote().
		Title("Charmburger").
		Description("Welcome to _Charmburger™_.\n\nHow may we take your order?").
		Next(true).
		NextLabel("Next"),
	),
	
	// Choose a burger.
	// We'll need to know what topping to add too.
	huh.NewGroup(
		huh.NewSelect[string]().
		Options(huh.NewOptions("Charmburger Classic", "Chickwich", "Fishburger", "Charmpossible™ Burger")...).
		Title("Choose your burger").
		Description("At Charm we truly have a burger for everyone.").
		Validate(func(t string) error {
			if t == "Fishburger" {
				return fmt.Errorf("no fish today, sorry")
			}
			return nil
		}).
		Value(&order.Burger.Type),
		
		huh.NewMultiSelect[string]().
		Title("Toppings").
		Description("Choose up to 4.").
		Options(
			huh.NewOption("Lettuce", "Lettuce").Selected(true),
			huh.NewOption("Tomatoes", "Tomatoes").Selected(true),
			huh.NewOption("Charm Sauce", "Charm Sauce"),
			huh.NewOption("Jalapeños", "Jalapeños"),
			huh.NewOption("Cheese", "Cheese"),
			huh.NewOption("Vegan Cheese", "Vegan Cheese"),
			huh.NewOption("Nutella", "Nutella"),
		).
		Validate(func(t []string) error {
			if len(t) <= 0 {
				return fmt.Errorf("at least one topping is required")
			}
			return nil
		}).
		Value(&order.Burger.Toppings).
		Filterable(true).
		Limit(4),
	),
	
	// Prompt for toppings and special instructions.
	// The customer can ask for up to 4 toppings.
	huh.NewGroup(
		huh.NewSelect[Spice]().
		Title("Spice level").
		Options(
			huh.NewOption("Mild", Mild).Selected(true),
			huh.NewOption("Medium", Medium),
			huh.NewOption("Hot", Hot),
		).
		Value(&order.Burger.Spice),
		
		huh.NewSelect[string]().
		Options(huh.NewOptions("Fries", "Disco Fries", "R&B Fries", "Carrots")...).
		Value(&order.Side).
		Title("Sides").
		Description("You get one free side with this order."),
	),
	
	// Gather final details for the order.
	huh.NewGroup(
		huh.NewInput().
		Value(&order.Name).
		Title("What's your name?").
		Placeholder("Margaret Thatcher").
		Validate(func(s string) error {
			if s == "Frank" {
				return errors.New("no franks, sorry")
			}
			return nil
		}).
		Description("For when your order is ready."),
		
		huh.NewText().
		Value(&order.Instructions).
		Placeholder("Just put it in the mailbox please").
		Title("Special Instructions").
		Description("Anything we should know?").
		CharLimit(400).
		Lines(5),
		
		huh.NewConfirm().
		Title("Would you like 15% off?").
		Value(&order.Discount).
		Affirmative("Yes!").
		Negative("No."),
	),
).WithAccessible(accessible)

err := form.Run()
if err != nil {
	fmt.Println("Uh oh:", err)
	os.Exit(1)
}

prepareBurger := func() {
	time.Sleep(2 * time.Second)
}

_ = spinner.New().Title("Preparing your burger...").WithAccessible(accessible).Action(prepareBurger).Run()

// Print order summary.
{
	var sb strings.Builder
	keyword := func(s string) string {
		return lipgloss.NewStyle().Foreground(lipgloss.Color("212")).Render(s)
	}
	fmt.Fprintf(&sb,
	"%s\n\nOne %s%s, topped with %s with %s on the side.",
	lipgloss.NewStyle().Bold(true).Render("BURGER RECEIPT"),
	keyword(order.Burger.Spice.String()),
	keyword(order.Burger.Type),
	keyword(xstrings.EnglishJoin(order.Burger.Toppings, true)),
	keyword(order.Side),
)

name := order.Name
if name != "" {
	name = ", " + name
}
fmt.Fprintf(&sb, "\n\nThanks for your order%s!", name)

if order.Discount {
	fmt.Fprint(&sb, "\n\nEnjoy 15% off.")
}

fmt.Println(
	lipgloss.NewStyle().
	Width(40).
	BorderStyle(lipgloss.RoundedBorder()).
	BorderForeground(lipgloss.Color("63")).
	Padding(1, 2).
	Render(sb.String()),
)
	}
}
```

### LINKED ISSUE #5604: darwin: x/sys `//go:cgo_import_dynamic` trampoline addresses are nil → SIGSEGV
In working through TinyGo+BubbleTea issues (#5365) , I originally went down the path of fixing the file-level linkname directive (#5401) as well as mucking with the Darwin Syscall interface (#5403), which was rightfully rejected although it also got BubbleTea to work.

With the linkname work merged and with fresh eyes, further research revealed why it was still broken and it involves yet another directive, `//go:cgo_import_dynamic`) that the Golang private syscall implementation uses in Darwin.   This directive is not properly implemented on any of the platforms, but it becomes detrimental to Darwin because of this detail.

We got an even simpler test case than #5365 and I have a PR forthcoming.

What remains is the LLM discussion of the issue, it's not exactly my voice, but I did work with it to uncover it and I've reviewed what it is saying.

----

## What happened

On darwin, any program that reaches libc through `golang.org/x/sys/unix` builds
successfully with TinyGo but segfaults at runtime with a call to address 0.

The highest-profile casualty: **every BubbleTea v2 / lipgloss v2 terminal app
crashes at startup on macOS native** — before `main()` even runs, because
`charmbracelet/colorprofile` calls `x/term.IsTerminal` (→ `unix.IoctlGetTermios`)
during package init. This is the current root cause behind the user reports in
#5365. (I believe this also affects anything else using x/sys on darwin:
`x/term`, raw-mode TUIs, etc.)

This is the next layer of the onion after #5401 (file-level `//go:linkname`,
merged — thanks!): the x/sys symbols now *link*, but the calls they make jump
through never-initialized function pointers.

## Minimal reproduction (no bubbletea required)

```go
package main

import (
	"fmt"

	"golang.org/x/sys/unix"
)

func main() {
	term, err := unix.IoctlGetTermios(1, unix.TIOCGETA)
	fmt.Println(term, err)
}
```

```
$ go mod init repro && go get golang.org/x/sys@v0.43.0
$ go build -o repro-go . && ./repro-go
&{...} inappropriate ioctl for device        # fine (or termios values on a tty)

$ tinygo build -o repro-tinygo . && ./repro-tinygo
panic: runtime error at 0x000000010236d978: nil pointer dereference
```

Reproduced with stock `dev` at f71b6305 (2026-08-20). Under lldb, the crash is
a branch to address 0 from the darwin syscall engine, with the ioctl arguments
already in place:

```
* thread #1, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000000000000
    frame #1: repro-stock`syscall.rawsyscalln + 60
    frame #2: repro-stock`syscall.syscall + 28
    frame #3: repro-stock`runtime.runMain + 940      (x/sys frames inlined)

pc = 0x0          ← branched to the trampoline pointer
x0 = 0x1          ← fd (stdout)
x1 = 0x40487413   ← TIOCGETA
```

## Diagnosis

x/sys on darwin dispatches every libc function through a per-function pointer
variable. For `ioctl` (x/sys `zsyscall_darwin_arm64.go` / `.s`):

```go
func ioctlPtr(fd int, req uint, arg unsafe.Pointer) (err error) {
	_, _, e1 := syscall_syscall(libc_ioctl_trampoline_addr, uintptr(fd), uintptr(req), uintptr(arg))
	...
}

var libc_ioctl_trampoline_addr uintptr

//go:cgo_import_dynamic libc_ioctl ioctl "/usr/lib/libSystem.B.dylib"
```

Upstream Go populates `libc_ioctl_trampoline_addr` from the companion `.s` file
(`DATA ·libc_ioctl_trampoline_addr(SB)/8, $libc_ioctl_trampoline<>(SB)`), whose
trampoline jumps to the dyld-bound `libc_ioctl` import declared by the
`//go:cgo_import_dynamic` pragma.

TinyGo assembles neither the `.s` file nor the pragma, so
`libc_ioctl_trampoline_addr` keeps its zero value. The call chain — which
otherwise works — then branches to address 0:

- `syscall_syscall` links fine now (#5401 handles the file-level linkname);
- TinyGo's own Go 1.26 engine (`src/runtime/os_darwin_go126.go`,
  `syscall.syscalln` / `syscall.rawsyscalln`) receives the call and faithfully
  invokes the `fn` it was handed;
- `fn == 0` → `EXC_BAD_ACCESS` at pc 0.

The full impact chain, from lldb on a tinygo-built bubbletea `spinner` example
(same crash, showing how it fires during package init before `main()`):

```
* thread #1, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000000000000
    frame #1: syscall.rawsyscalln + 60
    frame #2: syscall.syscall + 28
    frame #3: golang.org/x/sys/unix.ioctlPtr + 20
    frame #4: golang.org/x/sys/unix.IoctlGetTermios + 44
    frame #5: github.com/charmbracelet/x/term.IsTerminal + 8
    frame #6: github.com/charmbracelet/colorprofile.Detect + 240
    frame #7: runtime.initAll + 24468
    frame #8: runtime.runMain + 80

pc = 0x0          ← branched to the trampoline pointer
x0 = 0x1          ← fd (stdout)
x1 = 0x40487413   ← TIOCGETA
```

## Relationship to #5403 and public `syscall.Syscall*`

An earlier attempt in #5403 made public `syscall.Syscall*` calls work on darwin
by recognizing them as compiler intrinsics and emitting raw kernel syscall
instructions. That supplied a separate path for direct syscall-number callers:

```
syscall.Syscall(SYS_*, ...)
  → compiler lowering
  → raw svc/syscall instruction
  → darwin kernel
```

That approach bypassed darwin's libc-based route, ran against the maintainers'
preferred direction, and was not the path used by x/sys or BubbleTea. The x/sys
path is instead:

```
x/sys generated wrapper
  → libc_*_trampoline_addr
  → syscall.syscalln / syscall.rawsyscalln
  → libc function
```

After #5401 made x/sys's private linknames resolve, this reproducer showed that
TinyGo's existing libc dispatcher was already functional: execution reached it
with the correct `ioctl` arguments, but with `fn == 0`. In other words, the
dispatcher was not broken; the assembly-generated bridge that supplied its
libc function pointer was missing.

This issue completes that existing path by resolving the x/sys
`cgo_import_dynamic` trampoline address to the imported libc symbol. It does
not implement public `syscall.Syscall*`-by-number on darwin, which remains the
separate class of problem tracked in #4794.

There is **no userland workaround**: the trampoline-addr variables are defined
Go vars, so a `//go:linkname` push onto them fails with "symbol multiply
defined" — as @mparrett established in their excellent analysis on
https://github.com/tinygo-org/tinygo/issues/4794#issuecomment-4987489162 (their
"class 2" is exactly this bug; I'm filing it separately so it's searchable and
independently trackable — note the two classes are disjoint: this one is what
x/sys/BubbleTea needs, and it does not require `syscall.Syscall`-by-number
support).

## A second, silent gap: variadic imports on the existing stdlib path

While diagnosing this, a pre-existing bug surfaced on the trampoline path
TinyGo *does* implement. Of the symbols darwin's generated syscall wrappers
import, exactly `open`, `openat`, `fcntl`, and `ioctl` are variadic in the
Darwin SDK headers. TinyGo's syscall engine calls imported addresses through
fixed-signature function pointers (`tinygo_syscallX` in
`src/runtime/os_darwin.c`), which pass every argument in a register — but a
variadic callee reads its variadic arguments from the stack on darwin/arm64,
so a directly substituted variadic function receives garbage in the variadic
slot. The existing `createDarwinFuncPCABI0Call` lowering handles this only
for `open` (via the `syscall_libc_open` C wrapper), leaving the standard
library's `fcntl`, `ioctl`, and `openat` trampolines unsound.

Verified on stock `dev` at f71b6305 (darwin/arm64) with nothing but the
standard library: after `syscall.SetNonblock(fd, true)` — fcntl `F_SETFL`
with the new flags in the *variadic* slot — a read from the empty pipe still
blocks forever. An `F_GETFL` readback (run on a build that is identical on
this code path) measured garbage flags `0o20000110` instead of `0o4`. Unlike
the crash above, this fails silently. A fix for this issue naturally covers
both paths with the same wrapper set.

## Scope

This issue is specifically about the `//go:cgo_import_dynamic` pattern used by
darwin's generated syscall wrappers. The directive is not darwin-specific:
upstream Go also uses it on platforms such as OpenBSD, AIX, Solaris, and
illumos. A fix for this issue does not need to implement the directive as a
general cross-platform linker feature.

The targeted fix may parse the file-level directive to obtain its local and
remote symbol names, but should only perform the `libc_*_trampoline_addr`
symbol-address lowering for `GOOS=darwin`. Non-darwin targets should retain
their existing behavior. Supporting the directive's library operand, other
use patterns, and other platforms' linking and calling conventions is out of
scope and can be addressed separately.

## Possible fix directions

1. **Lower the darwin x/sys `//go:cgo_import_dynamic` pattern** — use the
   pragma's local and remote symbol names to replace loads of matching
   `libc_*_trampoline_addr` globals with the address of the dyld-bound symbol,
   extending TinyGo's existing darwin stdlib trampoline lowering. This does
   not require general implementation of the pragma's library operand.
   The `_ioctl` stub required by the fixed-signature wrapper is proposed in
   [macos-minimal-sdk#5](https://github.com/tinygo-org/macos-minimal-sdk/pull/5),
   together with the `___sincos_stret` stub surfaced by the Bubble Tea spinner
   verification. After that PR merges, TinyGo will also need a submodule bump.
   No new stubs are needed for the other variadic imports handled by the fix
   (`open`, `openat`, and `fcntl`), which are already in the SDK.

   One wrinkle: the variadic imports (`open`, `openat`, `fcntl`, `ioctl` —
   see "A second, silent gap" above) must be routed through fixed-signature
   C wrappers on this path too, the way the existing lowering already does
   for the standard library's `open`. A direct `ioctl` substitution
   observably fails with `EFAULT`.
2. Alternative: resolve at runtime via `dlsym(RTLD_DEFAULT, name)` during init
   (`dlsym` would itself need adding to the stub list).
3. Small orthogonal DX improvement regardless of the real fix: an `fn == 0`
   check in `os_darwin_go126.go`'s engine that panics with something like
   `"unresolved cgo_import_dynamic symbol"` instead of a raw SIGSEGV. Happy to
   send that as a standalone PR if wanted.

## Related

- #5365 — bubbletea/huh on macOS: this is its current root cause (linking is
  fixed by #5401; the crash remains).
- #4794 — public `syscall.Syscall`-by-number on darwin: disjoint symbol class,
  see @mparrett's comment there covering both.
- #5401 — file-level `//go:linkname` (merged), which exposed this next layer.
- [macos-minimal-sdk#5](https://github.com/tinygo-org/macos-minimal-sdk/pull/5)
  — companion `_ioctl` and `___sincos_stret` stubs; open as of 2026-08-22.

## Environment

- TinyGo: `tinygo version 0.42.0-dev darwin/arm64 (using go version go1.26.7
  and LLVM version 22.1.8)` — built from `dev` at f71b6305
- macOS: Darwin 25.6.0, arm64 (M-series)
- golang.org/x/sys v0.43.0
- Target: native darwin/arm64 (no `-target` flag)

### PR DESCRIPTION
**Pull request by neomantra**
As noted in #5604, this was worked through with LLM.  It adds parsing of the `go:cgo_import_dynamic` directive and implementation for Darwin. 

The other  Tinygo-supported platform that *could* use this is OpenBSD, but is more important for Darwin.  It targets `loadASTComments` generally because these directives are not necessarily attached to a function/module/etc; the comment there explains it.

The following description of the PR is LLM-generated from our journey; it is verbose but comprehensive.    I have read it and I have reviewed all the submitted code, both humanually and with multiple LLMs.   Thanks for the review.

----

## Summary

Extend TinyGo's existing Darwin stdlib trampoline lowering to the variable-based pattern used by `golang.org/x/sys/unix` and `internal/syscall/unix`, and route all four variadic libc imports (`open`, `openat`, `fcntl`, `ioctl`) through fixed-signature wrappers on both trampoline paths.

Fixes #5604.
Fixes #5365.
Builds on #5401.
The companion `_ioctl`/`___sincos_stret` stubs ([macos-minimal-sdk#5](https://github.com/tinygo-org/macos-minimal-sdk/pull/5)) are already in `dev` via the macos-minimal-sdk v0.1.0 submodule update.

## Problem

Darwin syscall wrappers generated by x/sys declare globals such as `libc_ioctl_trampoline_addr` and associate them with dylib symbols using file-level `//go:cgo_import_dynamic` pragmas. TinyGo does not compile the assembly that initializes those globals, so the existing libc syscall engine receives address zero and crashes before `main` in Bubble Tea programs.

TinyGo already avoids the equivalent assembly trampoline for the standard library: `createDarwinFuncPCABI0Call` recognizes `abi.FuncPCABI0(libc_*_trampoline)` and substitutes the address of an external libc declaration. This change applies that same lowering to the x/sys global-load pattern.

That existing stdlib lowering also carries a silent bug of its own: among its variadic imports it routes only `open` through a fixed-signature wrapper, so stdlib `fcntl`, `ioctl`, and `openat` calls corrupt their variadic arguments on darwin/arm64. This PR fixes that too, since the new lowering needs the same wrapper set anyway.

## Scope

This is a targeted implementation of the `//go:cgo_import_dynamic` pattern used by Darwin's generated syscall wrappers, not general cross-platform support for the directive. Although the file-level metadata is parsed during compilation, the `libc_*_trampoline_addr` symbol-address substitution is restricted to `GOOS=darwin`; non-Darwin targets retain their existing behavior.

Upstream Go also uses `//go:cgo_import_dynamic` on platforms such as OpenBSD, AIX, Solaris, and illumos. Supporting those platforms, the directive's library operand, other use patterns, and platform-specific linking or calling conventions remains out of scope.

## Implementation

- Parse the local and remote symbol metadata from file-level `//go:cgo_import_dynamic` pragmas into a package-local map for Darwin trampoline lowering, accepting the same one-, two-, and three-operand forms as the gc compiler (`local [remote ["library"]]`); the remote symbol defaults to the local one and the library operand is ignored (the linker already resolves against libSystem).
- On Darwin, replace loads of matching uintptr-typed `libc_*_trampoline_addr` globals with `ptrtoint` of an external declaration for the pragma's remote symbol. Globals of any other type keep their normal load.
- Preserve remote names verbatim, including amd64 `$INODE64` variants.
- Route the variadic imports through fixed-signature C wrappers via a shared `darwinVariadicImports` table. Of the symbols Darwin's generated syscall wrappers import (`zsyscall_darwin_*.go` in x/sys and the standard library), exactly `open`, `openat`, `fcntl`, and `ioctl` are variadic. The syscall engine calls imported addresses through fixed-signature function pointers (`tinygo_syscallX` and friends) that pass every argument in a register, while a variadic callee reads its variadic arguments from the stack on darwin/arm64, so direct calls silently receive garbage in the variadic slot (observed: `EFAULT` from `ioctl`; `unix.Open` creating files with mode 0 instead of the requested mode).
- In a separate commit, point the existing stdlib `FuncPCABI0` trampoline lowering (`createDarwinFuncPCABI0Call`) at the same table, replacing its `open`-only special case. This fixes the pre-existing silent bug on the stdlib path: `syscall.SetNonblock` (fcntl `F_SETFL` with the new flags in the variadic slot) observably wrote garbage file flags on darwin/arm64, and the stdlib `ioctl` and `openat` trampolines were equally unsound.
- Extend the focused compiler IR test: pragma parsing including the short directive forms, exact remote-symbol preservation, load replacement, wrapper routing for all four variadic imports (with no direct declarations for them), and the non-uintptr-global guard.

The companion `_ioctl` and `___sincos_stret` stub additions landed upstream in [macos-minimal-sdk#5](https://github.com/tinygo-org/macos-minimal-sdk/pull/5) and reached `dev` with the macos-minimal-sdk v0.1.0 submodule update, so this branch (rebased onto that dev) builds and links darwin x/sys programs out of the box with no SDK changes of its own. No new stubs are needed for `open`, `openat`, or `fcntl` — those symbols are already in the stock stub list, and their prototypes come from the SDK's `sys/fcntl.h`.

## Verification

- `go test -tags llvm22 ./compiler -count=1`
- 11-line `golang.org/x/sys/unix.IoctlGetTermios` repro under a PTY: returned a populated termios value and `<nil>`.
- `github.com/charmbracelet/x/term.IsTerminal` under a PTY: `true`.
- `term.MakeRaw` and `term.Restore` under a PTY: both `<nil>`.
- Bubble Tea `examples/spinner`: initialized, rendered animated frames, and exited on `q`.
- Bubble Tea `examples/list-default`: initialized, rendered the list UI, and exited on `q`.
- Variadic-slot checks (x/sys path), asserting values that travel through the variadic parameter: `unix.Open` with mode `0o640` created the file with mode `640` exactly, `unix.FcntlInt(F_DUPFD, 50)` returned fd `50`, and `unix.Openat` with mode `0o600` created mode `600` exactly. The pre-fix compiler produced mode `0`, fd `49`, and mode `41` on the same program — the silent-corruption failure mode.
- Variadic-slot check (stdlib `FuncPCABI0` path): `syscall.SetNonblock(fd, true)` followed by an `F_GETFL` readback yields flags exactly `0o4` (`O_NONBLOCK`), and a read from the empty pipe returns `EAGAIN` immediately. Without the `FuncPCABI0` change, the same program showed garbage flags (`0o20000110`), `O_NONBLOCK` unset, and the read blocked forever; the blocking read was also reproduced on stock `dev` at f71b6305 with a stdlib-only variant.

No startup panic or `os/signal`/SIGWINCH failure surfaced in this ladder.

## Context

This is the actual current Darwin-native root cause behind #5365. It is the "class 2" failure described by @mparrett in #4794 and is independent of the public `syscall.Syscall*` API discussed there.

An earlier attempt in #5403 made public `syscall.Syscall*` calls work by lowering syscall numbers directly to raw Darwin kernel instructions. That was a separate route which bypassed Darwin's libc-based dispatch and was never used by the x/sys/Bubble Tea call chain.

After #5401 made x/sys's private linknames resolve, the failing program reached TinyGo's existing `syscall.syscalln`/`syscall.rawsyscalln` libc dispatcher with the correct `ioctl` arguments but a zero function pointer. The dispatcher was not broken; the assembly-generated bridge that supplied its libc function pointer was missing. This change supplies that address and lets x/sys use TinyGo's existing libc path as intended.

This does not implement public `syscall.Syscall*`-by-number on Darwin, nor does it guarantee that every libc symbol is already present in the macOS minimal SDK.

### CODE REVIEW

**Comment by yohimik** [comment]
This also covers the stdlib fcntl fix in #5632. I will close that narrower duplicate and point the Darwin process work in #5634 here. The regression tests from #5632 remain available in src/os/fcntl_test.go at yohimik/tinygo@9161a8c6e75cb1444c21bee6e720a6605e39bc44. They cover integer F_SETFL and pointer F_GETLK arguments. Please reuse them if useful. I have read this implementation and its test record, but have not yet run those tests against this branch.

**Comment by yohimik** [comment]
Tested your head 08df1522 in the combined hosted candidate e7d34c8c, built by CI. The downloaded Darwin arm64 compiler builds unchanged Crier 7edaff9, and the earlier failure before main in x/sys/cpu.darwinSysctlEnabled is absent. Crier E2E passes 142 cases with no failures and one platform trust-store skip. The retained F_SETFL integer and F_GETLK pointer tests both pass, as do all process remapping tests. Full Linux and macOS candidate CI passed. This is combined-candidate evidence, not a claim that this PR alone supplies all Crier dependencies. Exact artifact IDs, hashes, logs, and limits are in https://github.com/yohimik/crier/blob/7c4ea43/docs/operations/tinygo-comparison-2026-09-05.md . Thank you for the broader stdlib and x/sys support.

**Comment by davecheney** [comment]
I verified this fix on osx/aarch64 with a project which previously panic'd using the x/term package and it worked. Thank you.

**Comment by deadprogram** [comment]
Thanks for this @neomantra, and for the very clear write-up. The approach looks correct, and the fix to the `open`-only special case in `createDarwinFuncPCABI0Call` is a good catch on its own.

The following findings are edited from an automated review.

**1. Link failures for x/sys symbols that have no stub**

`compileopts/target.go:411` sets `spec.Libc = "darwin-libSystem"` for all darwin builds, native and cross, so every darwin link goes through the stub `libSystem.dylib` built from `lib/macos-minimal-sdk`. Of the 147 unique remote symbols imported by the generated darwin syscall wrappers in the standard library and `x/sys/unix`, 39 have no stub:

```
accept bind clonefile clonefileat connect fclonefileat fgetxattr flistxattr
fremovexattr fsetxattr fstatfs getfsstat getpeername getsockname getsockopt
getxattr listen listxattr mount poll ptrace recvfrom recvmsg removexattr
sendfile sendmsg sendto setprivexec setsockopt setxattr shmat shmctl shmdt
shmget shutdown socket socketpair statfs unmount
```

Before this change, a live call to `unix.Socket` or `unix.Poll` loaded zero and failed at run time. After it, the compiler emits a real external declaration, so a live reference becomes an undefined-symbol link error. The new failure is earlier and clearer, but it is a behavior change for code that used to build. The PR puts stub coverage out of scope, which is reasonable. It would help to name the socket and xattr families in the description and to open a follow-up issue in `macos-minimal-sdk` for them.

**2. The `ioctl` declaration does not state its reason**

In `src/runtime/os_darwin.c`, `sys/ioctl.h` is not present in the minimal SDK, so the hand-written declaration is necessary. Please add a source reference on this comment. One line is enough:

```c
// <sys/ioctl.h> is not in lib/macos-minimal-sdk, so declare ioctl here.
extern int ioctl(int fd, unsigned long request, ...);
```

**3. Comment length**

Three new blocks are very long comments: `darwinVariadicImports` (17 lines), the pragma block in `loadASTComments` (14 lines), and the wrapper block in `os_darwin.c` (11 lines). The content is good, but most of it is rationale that reads better in the PR description. Each can go down to 2 lines plus the `sys/fcntl.h` reference.

**4. Wrapper signature style**

The three new wrappers take `uintptr_t` and cast inside, while the existing `syscall_libc_open` keeps typed parameters. Both work. Changing `syscall_libc_open` to match would keep the file uniform.

**5. Test hygiene**

`TestDarwinCgoImportDynamic` does not call `t.Parallel()` or `llvm.VerifyModule`, unlike the other tests in the file.

**6. Pragma position is not checked**

`strings.Fields(comment.Text)` accepts the directive in any comment, including a trailing comment on a code line. The gc compiler honors it only at column 1. This has no effect on the generated files that motivate the change.

**Comment by deadprogram** [comment]
@neomantra also please see merge conflict now, in addition to my last feedback. Thanks.

**Comment by deadprogram** [comment]
Thanks for the updates @neomantra.

All items from my last review are handled, and all CI checks pass. I also read the new error path in c6d1903e. When `createDarwinImportedFunctionAddr` reports the collision, both callers get a nil value and continue on the normal path, so the compiler records the error and does not panic.

The following finding was edited from an automated review.

**1. Stub coverage is still not recorded**

This is the item from my last review. I confirmed the behavior change. `unix.Socket` builds on `dev` today and faults at run time. On this branch the link stops:

```
zsyscall_darwin_arm64.go:105: linker could not find symbol _socket
```

The new failure is better. Perhaps you can open an issue in `macos-minimal-sdk` for this?

In any case, this PR is good now to merge. Thank you!
