### PR TITLE
syscall/js.FuncOf support

### PR DESCRIPTION
**Pull request by aykevl**

### CODE REVIEW

**Comment by aykevl** [comment]
Of course, this doesn't work well with Go 1.11 because `js.FuncOf` was only added in Go 1.12...

File: src/examples/wasm/export/wasm.go [hunk 1]
```diff
@@ -6,14 +6,21 @@ import (
...
+	document.Call("getElementById", "b").Set("oninput", updateCallback)
+	update()
 }
 
 //go:export add
 func add(a, b int) int {
 	return a + b
 }
 
-//go:export update
```
Comment (johanbrandhorst) [inline src/examples/wasm/export/wasm.go]: If this is no longer exported, this file is a poor example of the `export` method of interacting with webassembly :grimacing:

Comment (johanbrandhorst) [reply src/examples/wasm/export/wasm.go]: Oh I see the `add` method is still exported, nevermind!

**Comment by aykevl** [comment]
I was thinking that it may be better to add a new example that uses `js.FuncOf` instead of modifying the export example. That would also make it easier to fix the compilation error here.

**Comment by johanbrandhorst** [comment]
> I was thinking that it may be better to add a new example that uses `js.FuncOf` instead of modifying the export example. That would also make it easier to fix the compilation error here.

I think we could add it to the non-export example without making it too busy.

**Comment by aykevl** [comment]
New attempt, now more carefully written.

File: compiler/func-lowering.go [hunk 2]
```diff
@@ -154,17 +154,17 @@ func (c *Compiler) LowerFuncValues() {
 				// What we'll do is transform the following:
 				//     rawPtr := runtime.getFuncPtr(fn)
 				//     if func.rawPtr == nil {
-				//         runtime.nilpanic()
+				//         runtime.nilNanic()
```
Comment (johanbrandhorst) [inline compiler/func-lowering.go]: `nilPanic`?

Comment (aykevl) [reply compiler/func-lowering.go]: Oops will fix, thanks for the catch!

**Comment by aykevl** [comment]
I've now split the examples, it seems cleaner to me (although there is a bit of duplication). It clearly shows both ways of doing the same thing which may be useful.

@johanbrandhorst @justinclift any thoughts?

File: src/examples/wasm/callback/wasm.go [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+	"strconv"
+	"syscall/js"
+)
+
+func main() {
+	document := js.Global().Get("document")
+	updateCallback := js.FuncOf(func(this js.Value, args []js.Value) interface{} {
+		update()
+		return nil
+	})
```
Comment (johanbrandhorst) [inline src/examples/wasm/callback/wasm.go]: I think it would be better if we could show in the example the use of the parameters and the return value. Anyway we can expand this to include that?

Comment (aykevl) [reply src/examples/wasm/callback/wasm.go]: That's a good idea, do you have an idea what would be a good example?

File: compiler/func-lowering.go (hunk 2 above)
Comment (aykevl) [reply compiler/func-lowering.go]: Fixed.

File: src/examples/wasm/callback/wasm.go (hunk 3 above)
Comment (johanbrandhorst) [reply src/examples/wasm/callback/wasm.go]: Could we read the input from the parameters to this function instead of calling `getElementById`?

Comment (johanbrandhorst) [reply src/examples/wasm/callback/wasm.go]: What is this return value actually used for as well :thinking:?

Comment (aykevl) [reply src/examples/wasm/callback/wasm.go]: Callbacks can return something to JavaScript. However, I'm not sure why it is an `interface{}` and not a `js.Value`.

**Comment by aykevl** [comment]
I have updated the callback example to be more in a functional style. Not sure whether this example is much better but would like to hear some thoughts on it.

File: src/examples/wasm/callback/index.html [hunk 4]
```diff
@@ -0,0 +1,20 @@
...
+	<meta name="viewport" content="width=device-width, initial-scale=1" />
+	<script src="wasm_exec.js" defer></script>
+	<script src="wasm.js" defer></script>
+</head>
+
+<body>
+	<h1>WebAssembly</h1>
+	<p>Add two numbers, using WebAssembly:</p>
+	<input type="number" id="a" value="0" /> + <input type="number" id="b" value="0" /> = <input type="number"
+		id="result" readonly />
```
Comment (justinclift) [inline src/examples/wasm/callback/index.html]: It's a trivial thing, but maybe have the result input all be on one line?

**Comment by justinclift** [comment]
LGTM too.

`.Set("oninput", updater(&a))` is interesting too.  Didn't know that was a thing, having only mucked around with `.addEventListener("mousedown", someFunction)` before. :smile:

File: src/examples/wasm/callback/index.html (hunk 4 above)
Comment (aykevl) [reply src/examples/wasm/callback/index.html]: Fixed. Yes that's a bit unclean. (Probably some unintended auto-wrapping by my editor?)

**Comment by aykevl** [comment]
Yes, you can also set events by setting the `on`-prefixed property. However, this is generally discouraged for many things because it overwrites the old event handler. `addEventListener` was added specifically to avoid that.
