### ISSUE TITLE
Previously ok build (in 0.28.1) fails in 0.29.0 with "verification error after compiling" error

### ISSUE THREAD

**Issue by joeshaw** [tinygo-org/tinygo#3886]
If you check out https://github.com/fastly/compute-starter-kit-go-default at the current main ([0cc8e79](https://github.com/fastly/compute-starter-kit-go-default/commit/0cc8e7982027a276ee495ce86d313b28e54a97d8)) and compile it with `tinygo build -target=wasi -gc=conservative -o bin/main.wasm .` on TinyGo 0.29.0 with Go 1.20.7 (or 1.21) you'll get these errors:

```
Incorrect number of arguments passed to called function!
  %30 = call i32 @write(i32 %13, i32 %28, i32 %29, ptr %nWritten), !dbg !595
Incorrect number of arguments passed to called function!
  %16 = call i32 @lookup(i32 %8, i32 %14, i32 %15, ptr %13), !dbg !2334
Incorrect number of arguments passed to called function!
  %13 = call i32 @get(i32 %5, i32 %11, i32 %12, ptr %10), !dbg !2458
Call parameter type does not match function signature!
  %16 = extractvalue %"github.com/fastly/compute-sdk-go/internal/abi/prim.ArrayU8" %10, 0, !dbg !3130
 ptr  %18 = call i32 @lookup(i32 %16, i32 %17, i32 %13, ptr %14, ptr %15), !dbg !3130
Incorrect number of arguments passed to called function!
  %17 = call i32 @insert(i32 %15, i32 %16, i32 %12, ptr %13, ptr %14), !dbg !3156
error: verification error after compiling package github.com/fastly/compute-sdk-go/internal/abi/fastly
```

These errors weren't present in 0.28.1.

I've bisected the repo and it was commit d845f1e1b2f04b1c1e778bb7caac005967c1ed7c that first started causing these.

I haven't done more digging than this.  I am not sure if these errors are legitimate or not (though things seemed to be working fine with 0.28.1 and previous versions).

The code lives in https://github.com/fastly/compute-sdk-go/blob/v0.1.7/internal/abi/fastly/hostcalls_guest.go.

A newer version of the starter kit upgrades the Fastly SDK to 0.2.0, which moves to the new Go 1.21-compatible `go:wasmimport` scheme and that builds fine, but we would like to maintain compatibility with older versions of the SDK if possible.

**Comment by joeshaw** [comment]
That code is using both `//go:wasm-module` and `//export`, which d845f1e says is a no-no:

> `When a function is exported using //export, but also had a //go:wasm-module pragma, the //export name was ignored. The //go:wasm-module doesn't actually do anything besides breaking the export (exported functions don't have a module name).`

If you look in `hostcalls_guest.go` linked above, there are several functions with the same name in different wasm modules.  For instance, `lookup` appears in the `fastly_geo`, `fastly_object_store`, and `fastly_cache` modules.  It seems like specifying the module name in addition to the export name is necessary to distinguish between them.

**Comment by joeshaw** [comment]
The other functions listed in the error message also have multiple definitions in different modules with different parameter lists, which would explain why they appear.  For instance:

`write` in `fastly_http_body`: https://github.com/fastly/compute-sdk-go/blob/v0.1.7/internal/abi/fastly/hostcalls_guest.go#L239-L257

`write` in `fastly_log`: https://github.com/fastly/compute-sdk-go/blob/v0.1.7/internal/abi/fastly/hostcalls_guest.go#L373-L390

Dunno about the `prim.ArrayU8` error yet though.

**Comment by aykevl** [comment]
It appears that the `//export` pragmas that were previously ignored due to a bug, are now respected and as a result the code breaks. So the bug was always there, but surfaces only now because a bug in TinyGo prevented it from surfacing.

If that's the case, the easy fix would be to remove the `//export` declarations. Or at least rename them to something unique: the name has to be unique in the binary (not just a particular package).

**Comment by joeshaw** [comment]
I think part of the issue is that `//export` was overloaded for imports as well.  Removing the export lines gives linking errors, like:

```
tinygo:wasm-ld: error: /var/folders/8_/fzbgyzbj1d36ckz1mr8wkpj00000gp/T/tinygo674395257/main.o: undefined symbol: github.com/fastly/compute-sdk-go/internal/abi/fastly.fastlyGeoLookup
tinygo:wasm-ld: error: /var/folders/8_/fzbgyzbj1d36ckz1mr8wkpj00000gp/T/tinygo674395257/main.o: undefined symbol: github.com/fastly/compute-sdk-go/internal/abi/fastly.fastlyObjectStoreLookup
```

because now there is no association of those wasm symbols with the Go functions that implement them.

With 0.28.1, `wasm2wat` on a binary gives us entries like:

```
  (import "fastly_geo" "lookup" (func $github.com/fastly/compute-sdk-go/internal/abi/fastly.fastlyGeoLookup (type 14)))
  (import "fastly_object_store" "lookup" (func $github.com/fastly/compute-sdk-go/internal/abi/fastly.fastlyObjectStoreLookup (type 4)))
```

What I am ultimately hoping to achieve here is the biggest matrix of compatibility as possible.

In 0.28.1, the combination of `//export` and `//go:wasm-module` had the same effect that `//go:wasmimport` has today, _except_ for the stricter type checking which was previously more loosely permitted.

Right now we have a 0.1.x SDK that contains `//export` and `//go:wasm-module` and this works with TinyGo 0.26.0 to 0.28.1 but _not_ 0.29.0.  We have a 0.2.x SDK that contains `//go:wasmimport` that works with 0.28.1 and 0.29.0.  We'd prefer to be able to use 0.1.x with 0.29.0 for our users who continue to use the 0.1.x SDK but upgrade their TinyGo.  (We've already run into a couple users who've done this, and the error messages were perplexing.)

**Comment by deadprogram** [comment]
@joeshaw I'm pretty sure this was already resolved some versions ago, so can we close this issue?
